default:
	make -C convolution $@; \
	make -C convolution_separable $@; \
	make -C canny $@; \
	make -C hough $@; \
	make -C rotate $@; \

clean:
	make -C convolution $@; \
	make -C convolution_separable $@; \
	make -C canny $@; \
	make -C hough $@; \
	make -C rotate $@; \
