default:
	make -C backAdvect $@; \
	make -C bilateral $@; \
	make -C convolution $@; \
	make -C convolution_separable $@; \
	make -C canny $@; \
	make -C hough $@; \
	make -C demosaic $@; \
	make -C diff $@; \
	make -C lucaskanade $@; \
	make -C motionestimation $@; \
	make -C rotate $@; \

clean:
	make -C backAdvect $@; \
	make -C bilateral $@; \
	make -C convolution $@; \
	make -C convolution_separable $@; \
	make -C canny $@; \
	make -C hough $@; \
	make -C demosaic $@; \
	make -C diff $@; \
	make -C lucaskanade $@; \
	make -C motionestimation $@; \
	make -C rotate $@; \
