SRC := text.cpp ../util.cpp ../label/label.cpp
EXECUTABLE := text
#OBJECTS := ispc.o


include ../main.mk

#ispc.o: text.ispc
#	ispc text.ispc -wno-perf -o ispc.o -h ispc.h
#wno-perf disabled perf warning